"""coś nowego tam przyszło

Revision ID: 72350184a45d
Revises: 0a5d21b580e2
Create Date: 2022-07-14 10:34:17.415515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72350184a45d'
down_revision = '0a5d21b580e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
